// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCohYhxNULwDEdT2-feSCpiV6SaNWImZas',
    appId: '1:567994710024:web:05525543072315902239bd',
    messagingSenderId: '567994710024',
    projectId: 'janus-9501b',
    authDomain: 'janus-9501b.firebaseapp.com',
    storageBucket: 'janus-9501b.appspot.com',
    measurementId: 'G-K08DYDNV8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaDbR7stlPs_yroW8gZ0Z8PzioySex6gI',
    appId: '1:567994710024:android:345d9f1ea9ee6ea62239bd',
    messagingSenderId: '567994710024',
    projectId: 'janus-9501b',
    storageBucket: 'janus-9501b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbGufoLpHtuGTq37kA1mWv5P9ZiLfECO8',
    appId: '1:567994710024:ios:b47573bc8c30d8ac2239bd',
    messagingSenderId: '567994710024',
    projectId: 'janus-9501b',
    storageBucket: 'janus-9501b.appspot.com',
    iosBundleId: 'com.example.janus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbGufoLpHtuGTq37kA1mWv5P9ZiLfECO8',
    appId: '1:567994710024:ios:cc48273785718bad2239bd',
    messagingSenderId: '567994710024',
    projectId: 'janus-9501b',
    storageBucket: 'janus-9501b.appspot.com',
    iosBundleId: 'com.example.janus.RunnerTests',
  );
}
